export type SignalClassification = "selected" | "not_selected" | "waiting" | "noise";

export interface Signal {
  id: string;
  source_id: string;
  source_type: "post" | "comment";
  title: string;
  body: string;
  permalink: string;
  author: string;
  created_utc: string;
  score: number;
  flair: string | null;
  classification: SignalClassification;
  confidence: number;
  employer_mentions: string[];
  cap_type: string | null;
  extracted_at: string;
}

export const DEMO_SIGNALS: Signal[] = [
  {
    id: "1",
    source_id: "reddit_abc1",
    source_type: "post",
    title: "I GOT SELECTED!! FY2026 H1B Lottery",
    body: "Just checked my USCIS account — status changed to Selected! Cap-subject, employer is a large tech company. Good luck everyone still waiting!",
    permalink: "https://reddit.com/r/h1b/comments/abc1",
    author: "u/demo_user_0",
    created_utc: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    score: 92,
    flair: "Results",
    classification: "selected",
    confidence: 0.95,
    employer_mentions: ["Google"],
    cap_type: "Regular",
    extracted_at: new Date().toISOString(),
  },
  {
    id: "2",
    source_id: "reddit_abc2",
    source_type: "post",
    title: "Finally got selected after 3 years of trying",
    body: "My online account shows selected today. Master's cap. Been trying since FY2024. So relieved!",
    permalink: "https://reddit.com/r/h1b/comments/abc2",
    author: "u/demo_user_1",
    created_utc: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    score: 17,
    flair: "Results",
    classification: "selected",
    confidence: 0.92,
    employer_mentions: [],
    cap_type: "Master's",
    extracted_at: new Date().toISOString(),
  },
  {
    id: "3",
    source_id: "reddit_abc3",
    source_type: "post",
    title: "Not selected :( Back to square one",
    body: "Checked my account and it still shows Submitted then got an email saying not selected. Gutted.",
    permalink: "https://reddit.com/r/h1b/comments/abc3",
    author: "u/demo_user_2",
    created_utc: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    score: 141,
    flair: "Results",
    classification: "not_selected",
    confidence: 0.93,
    employer_mentions: [],
    cap_type: null,
    extracted_at: new Date().toISOString(),
  },
  {
    id: "4",
    source_id: "reddit_abc4",
    source_type: "post",
    title: "Still waiting — anyone else?",
    body: "It's been 3 days since the lottery was supposed to start and my status still says Submitted. Has anyone gotten an update yet?",
    permalink: "https://reddit.com/r/h1b/comments/abc4",
    author: "u/demo_user_3",
    created_utc: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    score: 166,
    flair: "Question",
    classification: "waiting",
    confidence: 0.88,
    employer_mentions: [],
    cap_type: null,
    extracted_at: new Date().toISOString(),
  },
  {
    id: "5",
    source_id: "reddit_abc5",
    source_type: "post",
    title: "Selected — 2nd time lottery entrant",
    body: "Got the notification this morning. Regular cap. Filed through a mid-size consulting firm.",
    permalink: "https://reddit.com/r/h1b/comments/abc5",
    author: "u/demo_user_4",
    created_utc: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    score: 34,
    flair: "Results",
    classification: "selected",
    confidence: 0.91,
    employer_mentions: ["Infosys"],
    cap_type: "Regular",
    extracted_at: new Date().toISOString(),
  },
  {
    id: "6",
    source_id: "reddit_abc6",
    source_type: "post",
    title: "Not selected again, 4th year",
    body: "This is my 4th time entering the lottery and still not selected. Starting to lose hope. Considering other options.",
    permalink: "https://reddit.com/r/h1b/comments/abc6",
    author: "u/demo_user_5",
    created_utc: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    score: 89,
    flair: "Results",
    classification: "not_selected",
    confidence: 0.94,
    employer_mentions: [],
    cap_type: null,
    extracted_at: new Date().toISOString(),
  },
  {
    id: "7",
    source_id: "reddit_abc7",
    source_type: "post",
    title: "My status just changed to Selected!",
    body: "Master's cap applicant. Amazon sponsored. Just saw the status change on my USCIS account!",
    permalink: "https://reddit.com/r/h1b/comments/abc7",
    author: "u/demo_user_6",
    created_utc: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    score: 45,
    flair: "Results",
    classification: "selected",
    confidence: 0.96,
    employer_mentions: ["Amazon"],
    cap_type: "Master's",
    extracted_at: new Date().toISOString(),
  },
  {
    id: "8",
    source_id: "reddit_abc8",
    source_type: "post",
    title: "Waiting since yesterday, no update",
    body: "Filed through my employer last week. Account still says Submitted. Is this normal?",
    permalink: "https://reddit.com/r/h1b/comments/abc8",
    author: "u/demo_user_7",
    created_utc: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    score: 23,
    flair: "Question",
    classification: "waiting",
    confidence: 0.85,
    employer_mentions: [],
    cap_type: null,
    extracted_at: new Date().toISOString(),
  },
  {
    id: "9",
    source_id: "reddit_abc9",
    source_type: "post",
    title: "Selected! Microsoft sponsorship",
    body: "Finally! After 2 years of trying. Regular cap through Microsoft. Don't give up hope everyone!",
    permalink: "https://reddit.com/r/h1b/comments/abc9",
    author: "u/demo_user_8",
    created_utc: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    score: 67,
    flair: "Results",
    classification: "selected",
    confidence: 0.97,
    employer_mentions: ["Microsoft"],
    cap_type: "Regular",
    extracted_at: new Date().toISOString(),
  },
  {
    id: "10",
    source_id: "reddit_abc10",
    source_type: "post",
    title: "Not selected — what are my options?",
    body: "Just got the email. Not selected for FY2026. What are the alternatives? Can I try again next year?",
    permalink: "https://reddit.com/r/h1b/comments/abc10",
    author: "u/demo_user_9",
    created_utc: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
    score: 112,
    flair: "Question",
    classification: "not_selected",
    confidence: 0.90,
    employer_mentions: [],
    cap_type: null,
    extracted_at: new Date().toISOString(),
  },
  {
    id: "11",
    source_id: "reddit_abc11",
    source_type: "post",
    title: "Selected — TCS sponsorship regular cap",
    body: "Got selected today. Regular cap through TCS. First time applicant.",
    permalink: "https://reddit.com/r/h1b/comments/abc11",
    author: "u/demo_user_10",
    created_utc: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    score: 28,
    flair: "Results",
    classification: "selected",
    confidence: 0.93,
    employer_mentions: ["TCS"],
    cap_type: "Regular",
    extracted_at: new Date().toISOString(),
  },
  {
    id: "12",
    source_id: "reddit_abc12",
    source_type: "post",
    title: "Still showing Submitted after 5 days",
    body: "Anyone else still waiting? My account hasn't changed at all. Getting anxious.",
    permalink: "https://reddit.com/r/h1b/comments/abc12",
    author: "u/demo_user_11",
    created_utc: new Date(Date.now() - 14 * 60 * 60 * 1000).toISOString(),
    score: 55,
    flair: "Question",
    classification: "waiting",
    confidence: 0.87,
    employer_mentions: [],
    cap_type: null,
    extracted_at: new Date().toISOString(),
  },
  {
    id: "13",
    source_id: "reddit_abc13",
    source_type: "post",
    title: "Not selected — employer says try again next year",
    body: "My employer confirmed I wasn't selected. They said they'll file again for FY2027.",
    permalink: "https://reddit.com/r/h1b/comments/abc13",
    author: "u/demo_user_12",
    created_utc: new Date(Date.now() - 16 * 60 * 60 * 1000).toISOString(),
    score: 76,
    flair: "Results",
    classification: "not_selected",
    confidence: 0.91,
    employer_mentions: [],
    cap_type: null,
    extracted_at: new Date().toISOString(),
  },
  {
    id: "14",
    source_id: "reddit_abc14",
    source_type: "post",
    title: "Selected! Meta new grad",
    body: "Just got notified! Master's cap through Meta. So happy right now!",
    permalink: "https://reddit.com/r/h1b/comments/abc14",
    author: "u/demo_user_13",
    created_utc: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
    score: 53,
    flair: "Results",
    classification: "selected",
    confidence: 0.95,
    employer_mentions: ["Meta"],
    cap_type: "Master's",
    extracted_at: new Date().toISOString(),
  },
  {
    id: "15",
    source_id: "reddit_abc15",
    source_type: "post",
    title: "Waiting — account shows no change",
    body: "Filed through a startup. Status still Submitted. Getting worried.",
    permalink: "https://reddit.com/r/h1b/comments/abc15",
    author: "u/demo_user_14",
    created_utc: new Date(Date.now() - 20 * 60 * 60 * 1000).toISOString(),
    score: 19,
    flair: null,
    classification: "waiting",
    confidence: 0.83,
    employer_mentions: [],
    cap_type: null,
    extracted_at: new Date().toISOString(),
  },
  {
    id: "16",
    source_id: "reddit_abc16",
    source_type: "post",
    title: "Selected regular cap — Apple",
    body: "My lawyer just confirmed I was selected. Regular cap through Apple. First attempt!",
    permalink: "https://reddit.com/r/h1b/comments/abc16",
    author: "u/demo_user_15",
    created_utc: new Date(Date.now() - 22 * 60 * 60 * 1000).toISOString(),
    score: 41,
    flair: "Results",
    classification: "selected",
    confidence: 0.94,
    employer_mentions: ["Apple"],
    cap_type: "Regular",
    extracted_at: new Date().toISOString(),
  },
  {
    id: "17",
    source_id: "reddit_abc17",
    source_type: "post",
    title: "Not selected — considering EB-1",
    body: "Didn't get selected again. Looking into EB-1 extraordinary ability category instead.",
    permalink: "https://reddit.com/r/h1b/comments/abc17",
    author: "u/demo_user_16",
    created_utc: new Date(Date.now() - 23 * 60 * 60 * 1000).toISOString(),
    score: 98,
    flair: "Discussion",
    classification: "not_selected",
    confidence: 0.89,
    employer_mentions: [],
    cap_type: null,
    extracted_at: new Date().toISOString(),
  },
  {
    id: "18",
    source_id: "reddit_abc18",
    source_type: "post",
    title: "Waiting — has anyone heard from small employers?",
    body: "My employer is a small startup with <50 employees. Still no update. Anyone in similar boat?",
    permalink: "https://reddit.com/r/h1b/comments/abc18",
    author: "u/demo_user_17",
    created_utc: new Date(Date.now() - 23.5 * 60 * 60 * 1000).toISOString(),
    score: 31,
    flair: "Question",
    classification: "waiting",
    confidence: 0.86,
    employer_mentions: [],
    cap_type: null,
    extracted_at: new Date().toISOString(),
  },
  {
    id: "19",
    source_id: "reddit_abc19",
    source_type: "post",
    title: "Selected — Deloitte master's cap",
    body: "Got the good news today! Master's cap through Deloitte. 2nd year trying.",
    permalink: "https://reddit.com/r/h1b/comments/abc19",
    author: "u/demo_user_18",
    created_utc: new Date(Date.now() - 23.8 * 60 * 60 * 1000).toISOString(),
    score: 36,
    flair: "Results",
    classification: "selected",
    confidence: 0.93,
    employer_mentions: ["Deloitte"],
    cap_type: "Master's",
    extracted_at: new Date().toISOString(),
  },
  {
    id: "20",
    source_id: "reddit_abc20",
    source_type: "post",
    title: "Not selected — 3rd consecutive year",
    body: "Another year, another rejection. Starting to consider O-1 or L-1 alternatives.",
    permalink: "https://reddit.com/r/h1b/comments/abc20",
    author: "u/demo_user_19",
    created_utc: new Date(Date.now() - 23.9 * 60 * 60 * 1000).toISOString(),
    score: 85,
    flair: "Results",
    classification: "not_selected",
    confidence: 0.92,
    employer_mentions: [],
    cap_type: null,
    extracted_at: new Date().toISOString(),
  },
];

export function getSignalsByTimeWindow(signals: Signal[], hours: number) {
  const cutoff = Date.now() - hours * 60 * 60 * 1000;
  return signals.filter(s => new Date(s.created_utc).getTime() > cutoff);
}

export function countByClassification(signals: Signal[]) {
  return {
    selected: signals.filter(s => s.classification === "selected").length,
    not_selected: signals.filter(s => s.classification === "not_selected").length,
    waiting: signals.filter(s => s.classification === "waiting").length,
    noise: signals.filter(s => s.classification === "noise").length,
  };
}
